CREATE TABLE app_sprite_defaults (
    sprite_key TEXT PRIMARY KEY,
    neutral_sprite TEXT NOT NULL,
    happy_sprite TEXT NOT NULL,
    angry_sprite TEXT NOT NULL,
    sleepy_sprite TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO app_sprite_defaults (
    sprite_key,
    neutral_sprite,
    happy_sprite,
    angry_sprite,
    sleepy_sprite
)
VALUES (
    'timeout_companion',
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAfUlEQVR4Ae3XQQqAMAwF0Yj3P7p3KiKXW0NMEVN6MCMGN28AL5OHnqd7qV3CyMfCVAA/gTBy06SnVAk0nnNAQCTKSeRykGGBqBPIDZiZsaAJ+lZeI7IuAvYi38DSHLVQQRIlnJrped1IovnEwlHGawEq+yLkOlLXg4Wr9PXgCulngkQCLOwBEmPA6kAMPxQAAAABJRU5ErkJggg==',
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAg0lEQVR4Ae3XQQrAIAwF0Vjv/5bdoo6gWQKUX++ImQxGc1dQc5sKXc5teLoI0AQwBfBz1uEeA1M0gijvOLLmQI0Aun1vDLteA94BhIqhzyapMI2Qxb38CAAXxrdbidKdvUSsfx8bVsgcQQIwCFwBnl2xe50Tzw9uQWGWpCJKaYG1ChcxrFAuo0xO+ogzAm8h1HnCA4VITQAAAABJRU5ErkJggg==',
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAgUlEQVR4Ae3XQQqAMAwF0In3P7q3ESyqCCpt5TRTF+t0NenE2no0Rvr0bUgA+A2MvmFo0xSg6u40qCMgCJLdnOjFkA7LI4gAl4AgzbIRbkIuAeGHNirMRqkRkNvztNFVQVwKP1HjqCOUMIqFZRMVAbAVYSEuxBjjcgzvEfgQ/HUkNzxaz2QmiFjCwCIRsEhDRbugzuDUFcAU9x6pRP70dAAAAAElFTkSuQmCC',
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAfElEQVR4Ae3XwQmAMAwF0In3P7o3G0KBPXn1HULICwhfQ3Gscx3rgIIB8A8BvYDn8ApX2HFqRSbAC5Mzdg3NofM8JrIoABNewWWm6yODgmQy4V/mAHMl1gLKYj1QLJsbgwe5caX5/C/PObbIVdQyQ9hBAB1FVOFAnhfvsIIRorAFz2uVH54camzAAAAAElFTkSuQmCC'
)
ON CONFLICT (sprite_key) DO NOTHING;
